apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: hadilbenm/backend-feed:v1
          envFrom:
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: env-configmap
          ports:
            - containerPort: 8080
